"""Generate SUMO demand for the ORR corridor (docs/08 §6).

    python sumo/gen_routes.py --demand medium --amb-depart 300 --out sumo/routes_medium.rou.xml

Demand levels (veh/h per direction), inside the docs/08 §6 ranges:
    low: main 900, cross 300 | medium: main 1200, cross 450 | peak: main 1500, cross 600
Arrivals are Poisson (SUMO `period="exp(rate)"`); the random stream is fixed by the
`--seed` passed to SUMO at run time, not by this file.
Vehicle mix: car 60%, two-wheeler 30%, bus/truck 10%.
One ambulance (vClass=emergency) enters at entry_west at `--amb-depart` seconds;
the RL env varies this offset per episode.

[ASSUMPTION] Vehicle parameters (lengths, speed factors, ambulance speedFactor 1.3 and
impatience 1.0) are SUMO-style defaults chosen by the team, not measured Bengaluru values.
[ASSUMPTION] Background traffic goes straight through (no turning); only the demand
counts in docs/08 §6 are specified.
"""
from __future__ import annotations

import argparse
from pathlib import Path

JUNCTIONS = ("silkboard", "bellandur", "marathahalli", "krpuram")
DEMAND = {  # veh/h: (main line per direction, each cross-street direction)
    "low": (900, 300),
    "medium": (1200, 450),
    "peak": (1500, 600),
}
VEHICLE_MIX = {"car": 0.6, "two_wheeler": 0.3, "bus_truck": 0.1}
SIM_END_S = 3600  # flows run for 1 h; episodes need >= 1800 s (docs/08 §6)

MAIN_EB = ("entry_west_silkboard silkboard_bellandur bellandur_marathahalli "
           "marathahalli_krpuram krpuram_exit_east")
MAIN_WB = ("exit_east_krpuram krpuram_marathahalli marathahalli_bellandur "
           "bellandur_silkboard silkboard_entry_west")

VTYPES = """\
    <vTypeDistribution id="background">
        <vType id="car" vClass="passenger" length="4.5" accel="2.6" decel="4.5" sigma="0.5" speedDev="0.1" probability="{car}"/>
        <vType id="two_wheeler" vClass="motorcycle" length="2.0" accel="3.0" decel="5.0" sigma="0.5" speedDev="0.1" probability="{two_wheeler}"/>
        <vType id="bus_truck" vClass="truck" length="10.0" accel="1.2" decel="4.0" sigma="0.5" speedDev="0.05" probability="{bus_truck}"/>
    </vTypeDistribution>
    <vType id="ambulance" vClass="emergency" guiShape="emergency" length="5.5" accel="3.0" decel="5.0" sigma="0" speedFactor="1.3" impatience="1.0" color="1,0,0"/>
"""


def build_routes(demand: str, amb_depart: float) -> str:
    if demand not in DEMAND:
        raise ValueError(f"demand must be one of {list(DEMAND)}, got {demand!r}")
    if not 0 <= amb_depart <= SIM_END_S - 1800:
        raise ValueError(f"amb_depart must be in [0, {SIM_END_S - 1800}] s so it can clear the corridor")
    main_vph, cross_vph = DEMAND[demand]

    routes = [("main_eb", MAIN_EB, main_vph), ("main_wb", MAIN_WB, main_vph)]
    for j in JUNCTIONS:
        routes.append((f"{j}_nb", f"{j}_s_{j} {j}_{j}_n", cross_vph))
        routes.append((f"{j}_sb", f"{j}_n_{j} {j}_{j}_s", cross_vph))

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             f"<!-- generated by sumo/gen_routes.py: demand={demand}, amb_depart={amb_depart:g} s -->",
             "<routes>", VTYPES.format(**VEHICLE_MIX).rstrip()]
    lines += [f'    <route id="{rid}" edges="{edges}"/>' for rid, edges, _ in routes]
    lines += [
        f'    <flow id="f_{rid}" route="{rid}" type="background" begin="0" end="{SIM_END_S}" '
        f'period="exp({vph / 3600:.6f})" departLane="best" departSpeed="max"/>'
        for rid, _, vph in routes
    ]
    lines.append(f'    <vehicle id="ambulance" type="ambulance" route="main_eb" depart="{amb_depart:g}" '
                 'departLane="best" departSpeed="max"/>')
    lines.append("</routes>")
    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--demand", choices=list(DEMAND), default="medium")
    p.add_argument("--amb-depart", type=float, default=300.0)
    p.add_argument("--out", type=Path)
    a = p.parse_args()
    out = a.out or Path(__file__).parent / f"routes_{a.demand}.rou.xml"
    out.write_text(build_routes(a.demand, a.amb_depart), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
